apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--kuma-metrics
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-imac'
    path: kuma-metrics
    targetRevision: master
  destination:
    name: imac
    namespace: kuma-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
